### ISSUE TITLE
Mandrill API Change

### ISSUE THREAD

**Issue by nelsonic** [besarthoxhaj/sail-back#232]
http://blog.mandrill.com/important-changes-to-mandrill.html
Might be worth checking: https://mandrill.zendesk.com/hc/en-us/articles/217600288

**Comment by sofer** [comment]
@nelsonic well spotted. 

@rjmk Mailgun or SparkPost are two other possibilities (see https://github.com/foundersandcoders/mail-fac/issues/4 for a cheeky sales pitch from SparkPost).

**Comment by rjmk** [comment]
Thanks, @nelsonic @sofer!

**Comment by rjmk** [comment]
Actually I think [we're using Mailgun](https://github.com/foundersandcoders/sail-back/blob/master/api/services/Email_mailgun.js), and the mandrill dep is just legacy. Will look into this soon

**Comment by nelsonic** [comment]
@rjmk menos mal. 
so a dependency prune _might_ be all that's required...
https://github.com/foundersandcoders/sail-back/blob/e5350d0cdd47e0954f9f94db80b5e4c1f519d371/package.json#L54 :+1:
