### ISSUE TITLE
Linting Standards

### ISSUE THREAD

**Issue by ivan-unfolds** [besarthoxhaj/sail-back#265]
Need to come up with some linting standards as I would love to have a linter.

**Comment by rjmk** [comment]
Hey, @ivanmauricio! Can you say a little more about why you want a linter? I don't use one, so it's hard to know what we should be aiming for on the linter to make sure you get what you need out of it.

Some notes on the projects style so far:
- Multiline object literals, array literals and function calls follow Elm-style layout. That is, first line is the opening bracket, indented once, followed by a space and the first entry / argument / etc. Following lines are also indented and begin with a comma. **Advantages**:
  - Painless alignment (for neatness)
  - Clean diffs (you normally are not adding something to the front of such a list, so you rarely need to add a diff to an unchanged line; also, we don't get pure alignment diffs)
- Destructured imports do not do this, and line-wrap where  possible
- Lines are wrapped at 79 characters (80 including newline)

**Comment by rjmk** [comment]
So, I've realised you guys are taking up this project, so if you want a linter, go for it!

If you want my advice on config, use [standard](https://github.com/feross/standard). Also, let's do a single 'Linting' commit that updates the whole project to linting standards
