### ISSUE TITLE
Flow hanging on Travis and dev computers

### ISSUE THREAD

**Issue by rjmk** [besarthoxhaj/sail-back#268]
Flow is hanging on the Travis builds and on @ivanmauricio and @JMurphyWeb's computers.

Let's do some debugging!

Some info that would be useful:
- What is the output of `flow version` / `./node_modules/.bin/flow version`?
- If you checkout to master, to the tests still hang?

**Comment by ivan-unfolds** [comment]
@rjmk did you get my email?

**Comment by rjmk** [comment]
Hi, @ivanmauricio. Sorry, I've been a bit disconnected today. Got your email about the versions and the fact that `flow` works locally. Have you tried checking out to `master`?
