### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by nelsonic** [besarthoxhaj/sail-back#394]
Morning _Sail-backers_, was reading the NodeSecurity Advisories and noted that `sails` has a `CORS` vulnerability:
![node-security-advisory-sails-cors](https://cloud.githubusercontent.com/assets/194400/19639266/aaaba058-99cf-11e6-861e-86f713370935.png)

see: https://nodesecurity.io/advisories/148 and https://david-dm.org/foundersandcoders/sail-back [![dependencies Status](https://david-dm.org/foundersandcoders/sail-back/status.svg)](https://david-dm.org/foundersandcoders/sail-back)

At present your `config/cors.js` has the two "_offending_" settings _commented out_:
https://github.com/foundersandcoders/sail-back/blob/2be6b3df628c9dbb6c8976bb123cebc993ffa88c/config/cors.js#L40 so there isn't an _immediate_ threat of unauthorised activity. 

However it _might_ be worth prioritising ...
- [ ] update dependencies to latest version(s) to avoid security issues.

**Comment by ivan-unfolds** [comment]
@nelsonic Thanks for the heads up! Not sure what this entails but will investigate.

**Comment by nelsonic** [comment]
@ivanmauricio _hopefully_ it's "_just_" a matter of updating the dependencies in `package.json` then `npm install` and `npm test` letting your `tests` do the _work_ of checking that the app still works as expected/required... 😉

**Comment by ivan-unfolds** [comment]
@nelsonic I have now updated Sails via #398.

**Comment by nelsonic** [comment]
@ivanmauricio nice one. it's _always_ a good idea to keep a regular check on dependencies. 😉
