### ISSUE TITLE
anmp: can add new member

### ISSUE THREAD

**Issue by rjmk** [besarthoxhaj/sail-back#43]
with auto-generate membership number

**Comment by FilWisher** [comment]
Editing: 
- test/react/admin/pages/add_member.test.js
- src/admin/pages/add_member.js

**Comment by FilWisher** [comment]
- [x] split form
- [x] onchange handler
- [x] onsave handler
- [ ] prefill member-id
- [ ] correct input types
- [ ] validate inputs
