### ISSUE TITLE
End membership link in email

### ISSUE THREAD

**Issue by jay-meister** [besarthoxhaj/sail-back#519]
All emails should offer the user the option to 'End their membership' via  link at the bottom.

**Comment by jay-meister** [comment]
<img width="762" alt="screen shot 2017-07-27 at 11 52 17" src="https://user-images.githubusercontent.com/12638261/28667129-133a076a-72c2-11e7-84fb-d97e1f5f3792.png">

**Comment by jay-meister** [comment]
@dicul I have updated the copy as you asked. 

I will soon send you a demo email from the app running locally.

**Comment by Dicul** [comment]
All three emails look good.  Thanks Jack

**Comment by jay-meister** [comment]
Closing as Richard has agreed emails are fine 👍
